name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run pipeline on pushes to 'main'
  pull_request:
    branches:
      - main  # Run pipeline on PRs to 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/CICDPROJECT
            git pull origin main
            source django_env/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            systemctl restart CICDDJANGO.service
